CREATE TABLE students (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      surname VARCHAR(255) NOT NULL,
      patronymic VARCHAR(255) NOT NULL,
      first_name VARCHAR(255) NOT NULL,
      class_id BIGINT NOT NULL,
      CONSTRAINT fk_student_class FOREIGN KEY (class_id) REFERENCES school_classes(id)
);