CREATE TABLE timetables (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   teacher_id BIGINT NOT NULL,
   subject_id BIGINT NOT NULL,
   class_id BIGINT NOT NULL,
   classroom_id BIGINT NOT NULL,
   day_of_week VARCHAR(20) NOT NULL,
   start_time TIME NOT NULL,
   lesson_number INT NOT NULL,
   CONSTRAINT fk_tt_teacher FOREIGN KEY (teacher_id) REFERENCES teachers(id),
   CONSTRAINT fk_tt_subject FOREIGN KEY (subject_id) REFERENCES subject(id),
   CONSTRAINT fk_tt_class FOREIGN KEY (class_id) REFERENCES school_classes(id),
   CONSTRAINT fk_tt_classroom FOREIGN KEY (classroom_id) REFERENCES classrooms(id)
);